create TABLE IF NOT EXISTS genre (
  id integer PRIMARY KEY,
  name varchar(63) NOT NULL
);

create TABLE IF NOT EXISTS mpa_rating (
  mpa_rating_id integer PRIMARY KEY,
  mpa_name varchar(63) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS film (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description text,
  releaseDate date,
  duration integer CHECK (duration > 0),
  mpa_id integer NOT NULL REFERENCES mpa_rating (mpa_rating_id)
);

create TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL,
  login varchar(255) NOT NULL UNIQUE,
  name varchar(255),
  birthday date
);

create TABLE IF NOT EXISTS friendship (
  user_id1 integer NOT NULL REFERENCES users(id) ON delete CASCADE,
  user_id2 integer NOT NULL REFERENCES users(id) ON delete CASCADE,
  PRIMARY KEY (user_id1, user_id2)
);

create TABLE IF NOT EXISTS film_genre (
  film_id bigint REFERENCES film (id) NOT NULL,
  genre_id integer REFERENCES genre (id) NOT NULL
);

create TABLE IF NOT EXISTS likes (
  film_id bigint REFERENCES film (id) NOT NULL,
  user_id bigint REFERENCES users (id) NOT NULL
);